initial_screen = "library"

library_tabs = ["playlists", "podcasts", "artists"]

repeat = "playlist"

hide_display_names = true

statusbar_format = "%artists - %title"

[track_format]
left = "%artists - %title"
center = "%album"
right = "%duration"

[theme]
primary = "light white"
secondary = "light black"
title = "green"
playing = "green"
playing_bg = "black"
highlight = "light white"
highlight_bg = "#484848"
error = "light white"
error_bg = "red"
statusbar = "black"
statusbar_progress = "green"
statusbar_bg = "green"
cmdline = "light white"
cmdline_bg = "black"

[credentials]
username_cmd = "echo fefepenn@gmail.com"
password_cmd = "bw get password spotify"
